crossfit-api:
  build: .
  ports:
    - 3000:3000
  links:
    - crossfit-rethink:rethink
  environment:
    - PORT=3000
    - DB_HOST=rethink
crossfit-rethink:
  image: rethinkdb
  ports:
    - 8080:8080
